import Head from 'next/head'
import Image from 'next/image'

export default function Home() {

  const userName = 'Marcos';
    const pessoasComentarios = [
      'juunegreiros',
      'omariosouto',
      'peas',
      'rafaballerini',
      'marcobrunodev',
      'felipefialho'
  ]

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="comments">
        <div className="comments--title">
            <h3>Caixa de comentários</h3>
        </div>
            <div className="comments--form">
              <form>
                <div>
                    <input
                        placeholder="Nome do Github"
                        name="name"
                        aria-lavel="Nome do Github"
                        type="text" />
                    
                </div>
                <div>
                    <input
                        placeholder="Qual o seu comentário"
                        name="coment"
                        aria-lavel="Qual o seu comentário"
                        type="text"/>
                </div>
              <button>
                  Adicionar comentário
              </button>
            </form>
        </div>

        <div className="comments--usercoments">
            <div className="comments--comments">
                <ul>
                    {pessoasComentarios.map((itemAtual) => {
                        return (
                            <li>
                                <a href={`/users/${itemAtual}`} key={itemAtual}><img src={`https://github.com/${itemAtual}.png`} alt={itemAtual}/></a>
                                    <div className="comments--dados">
                                        <span>@{itemAtual}</span>
                                        <p>Comentário de {itemAtual}</p>
                                    </div>
                            </li>
                            )
                    })}
                </ul>
            </div>
        </div>
    </div>
  </div>
  )
}
